Use CLI to validate minimal RBAC tests instead of testim

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -697,37 +697,118 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        cluster: ${{ fromJson(needs.cmx-versions.outputs.versions-to-test) }}
-    continue-on-error: ${{ matrix.cluster.stage != 'stable' }}
+        cluster: [
+          {distribution: kind, version: v1.28.0},
+          {distribution: openshift, version: 4.13.0-okd}
+        ]
+    env:
+      APP_SLUG: minimal-rbac
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: download e2e deps
-        uses: actions/download-artifact@v3
+
+      - name: Create Cluster 
+        id: create-cluster 
+        uses: replicatedhq/replicated-actions/create-cluster@v1 
         with:
-          name: e2e
-          path: e2e/bin/
-      - run: docker load -i e2e/bin/e2e-deps.tar
-      - run: chmod +x e2e/bin/*
+          api-token: ${{ secrets.C11Y_MATRIX_TOKEN }}
+          kubernetes-distribution: ${{ matrix.cluster.distribution }}
+          kubernetes-version: ${{ matrix.cluster.version }}
+          cluster-name: automated-kots-${{ github.run_id }}-${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
+          timeout-minutes: '120'
+          ttl: 2h
+          export-kubeconfig: true
+
       - name: download kots binary
         uses: actions/download-artifact@v3
         with:
           name: kots
           path: bin/
-      - run: chmod +x bin/*
-      - uses: ./.github/actions/kots-e2e
+
+      - run: chmod +x bin/kots
+
+      - name: create namespace and dockerhub secret
+        run: |
+          kubectl create ns "$APP_SLUG"
+          kubectl create secret docker-registry kotsadm-dockerhub --docker-server index.docker.io --docker-username "${{ secrets.E2E_DOCKERHUB_USERNAME }}" --docker-password "${{ secrets.E2E_DOCKERHUB_PASSWORD }}" --namespace "$APP_SLUG"
+
+      - name: run the test
+        run: |
+          set +e
+          echo ${{ secrets.MINIMAL_RBAC_LICENSE }} | base64 -d > license.yaml
+          ./bin/kots \
+            install "$APP_SLUG/automated" \
+            --license-file license.yaml \
+            --no-port-forward \
+            --namespace "$APP_SLUG" \
+            --shared-password password \
+            --kotsadm-registry ttl.sh \
+            --kotsadm-namespace automated-${{ github.run_id }} \
+            --skip-preflights \
+            --kotsadm-tag 24h
+
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "------pods:"
+            kubectl -n "$APP_SLUG" get pods
+            echo "------kotsadm logs"
+            kubectl logs -l app=kotsadm --tail=100 --namespace "$APP_SLUG"
+            exit $EXIT_CODE
+          fi
+
+          COUNTER=1
+          while [ "$(./bin/kots get apps --namespace "$APP_SLUG" | awk 'NR>1{print $2}')" != "ready" ]; do
+            ((COUNTER += 1))
+            if [ $COUNTER -gt 180 ]; then
+              echo "Timed out waiting for app to be ready"
+              ./bin/kots get apps --namespace "$APP_SLUG"
+              echo "kotsadm logs:"
+              kubectl logs -l app=kotsadm --tail=100 --namespace "$APP_SLUG"
+              exit 1
+            fi
+            sleep 1
+          done
+
+          if ! kubectl get role -n "$APP_SLUG" | grep -q kotsadm; then
+            echo "kotsadm role not found in namespace $APP_SLUG"
+            kubectl get role -n "$APP_SLUG"
+            exit 1
+          fi
+
+          if ! kubectl get rolebinding -n "$APP_SLUG" | grep -q kotsadm; then
+            echo "kotsadm rolebinding not found in namespace $APP_SLUG"
+            kubectl get rolebinding -n "$APP_SLUG"
+            exit 1
+          fi
+
+          if kubectl get clusterrole | grep -q kotsadm; then
+            echo "found kotsadm clusterrole in minimal RBAC install"
+            kubectl get clusterrole
+            exit 1
+          fi
+
+          if kubectl get clusterrolebinding | grep -q kotsadm; then
+            echo "found kotsadm clusterrolebinding in minimal RBAC install"
+            kubectl get clusterrolebinding
+            exit 1
+          fi
+
+      - name: Generate support bundle on failure
+        if: failure()
+        uses: ./.github/actions/generate-support-bundle
         with:
-          test-focus: 'Minimal RBAC'
-          kots-namespace: 'minimal-rbac'
-          k8s-distribution: ${{ matrix.cluster.distribution }}
-          k8s-version: ${{ matrix.cluster.version }}
-          testim-access-token: '${{ secrets.TESTIM_ACCESS_TOKEN }}'
-          testim-branch: ${{ github.head_ref == 'main' && 'master' || github.head_ref }}
+          kots-namespace: "$APP_SLUG"
           aws-access-key-id: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_ACCESS_KEY_ID }}'
           aws-secret-access-key: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_SECRET_ACCESS_KEY }}'
-          replicated-api-token: '${{ secrets.C11Y_MATRIX_TOKEN }}'
-          kots-dockerhub-username: '${{ secrets.E2E_DOCKERHUB_USERNAME }}'
-          kots-dockerhub-password: '${{ secrets.E2E_DOCKERHUB_PASSWORD }}'
+
+      - name: Remove Cluster
+        id: remove-cluster
+        uses: replicatedhq/replicated-actions/remove-cluster@v1
+        if: ${{ always() && steps.create-cluster.outputs.cluster-id != '' }}
+        continue-on-error: true
+        with:
+          api-token: ${{ secrets.C11Y_MATRIX_TOKEN }}
+          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
 
 
   validate-backup-and-restore:
@@ -776,7 +857,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -816,7 +897,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     env:
       APP_SLUG: strict-preflight-checks
@@ -925,7 +1006,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -1004,7 +1085,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -1043,8 +1124,10 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        cluster: ${{ fromJson(needs.cmx-versions.outputs.versions-to-test) }}
-    continue-on-error: ${{ matrix.cluster.stage != 'stable' }}
+        cluster: [
+          {distribution: kind, version: v1.28.0},
+          {distribution: openshift, version: 4.13.0-okd}
+        ]
     env:
       APP_SLUG: minimal-rbac
       APP_VERSION_LABEL: "0.0.1"
@@ -1090,15 +1173,29 @@ jobs:
             --kotsadm-namespace automated-${{ github.run_id }} \
             --kotsadm-tag 24h \
             --use-minimal-rbac
-          if kubectl get roles -n "$APP_SLUG" | grep -q kotsadm; then
-            echo "Found kotsadm role in ${APP_SLUG}"
-          else
-            echo "No kotsadm role found in appication namespace"
+
+          if ! kubectl get role -n "$APP_SLUG" | grep -q kotsadm; then
+            echo "kotsadm role not found in namespace $APP_SLUG"
+            kubectl get role -n "$APP_SLUG"
             exit 1
           fi
-          if kubectl get clusterroles | grep -q kotsadm; then
-            echo "Found kotsadm cluster roles in minimal RBAC install"
-            exit
+
+          if ! kubectl get rolebinding -n "$APP_SLUG" | grep -q kotsadm; then
+            echo "kotsadm rolebinding not found in namespace $APP_SLUG"
+            kubectl get rolebinding -n "$APP_SLUG"
+            exit 1
+          fi
+
+          if kubectl get clusterrole | grep -q kotsadm; then
+            echo "found kotsadm clusterrole in minimal RBAC install"
+            kubectl get clusterrole
+            exit 1
+          fi
+
+          if kubectl get clusterrolebinding | grep -q kotsadm; then
+            echo "found kotsadm clusterrolebinding in minimal RBAC install"
+            kubectl get clusterrolebinding
+            exit 1
           fi
 
       - name: create namespace and dockerhub secret
@@ -1118,16 +1215,31 @@ jobs:
             --kotsadm-registry ttl.sh \
             --kotsadm-namespace automated-${{ github.run_id }} \
             --kotsadm-tag 24h
-          if kubectl get roles -n "$APP_SLUG" | grep -q kotsadm; then
-            echo "Found kotsadm role in cluster scoped install"
+
+          if kubectl get role -n "$APP_SLUG" | grep -q kotsadm; then
+            echo "kotsadm role found in cluster scoped install"
+            kubectl get role -n "$APP_SLUG"
             exit 1
           fi
-          if kubectl get clusterroles | grep -q kotsadm; then
-            echo "Found kotsadm cluster role in cluster scoped install"
-          else
-            echo "No kotsadm cluster role in cluster scoped install"
+
+          if kubectl get rolebinding -n "$APP_SLUG" | grep -q kotsadm; then
+            echo "kotsadm rolebinding found in cluster scoped install"
+            kubectl get rolebinding -n "$APP_SLUG"
             exit 1
           fi
+
+          if ! kubectl get clusterrole | grep -q kotsadm; then
+            echo "No kotsadm clusterrole found in cluster scoped install"
+            kubectl get clusterrole
+            exit 1
+          fi
+
+          if ! kubectl get clusterrolebinding | grep -q kotsadm; then
+            echo "No kotsadm clusterrolebinding found in cluster scoped install"
+            kubectl get clusterrolebinding
+            exit 1
+          fi
+
       - name: Generate support bundle on failure
         if: failure()
         uses: ./.github/actions/generate-support-bundle
@@ -1375,7 +1487,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     env:
       APP_SLUG: app-version-label
@@ -1632,7 +1744,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     env:
       APP_SLUG: no-redeploy-on-restart
@@ -1754,7 +1866,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     env:
       APP_SLUG: kubernetes-installer-preflight
@@ -1891,7 +2003,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -1952,7 +2064,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     env:
       APP_SLUG: minimal-rbac
@@ -2149,7 +2261,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -2217,7 +2329,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -2284,7 +2396,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -2490,7 +2602,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     env:
       APP_SLUG: helm-release-secret-migration
@@ -2677,7 +2789,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -2717,7 +2829,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -2757,7 +2869,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27}
+          {distribution: kind, version: v1.28.0}
         ]
     steps:
       - name: Checkout
@@ -2798,7 +2910,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27, instance-type: r1.medium}
+          {distribution: kind, version: v1.28.0, instance-type: r1.medium}
         ]
     env:
       APP_SLUG: remove-app
@@ -2977,7 +3089,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     steps:
       - name: Checkout
@@ -3072,7 +3184,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     env:
       APP_SLUG: native-helm-v2
@@ -3298,7 +3410,7 @@ jobs:
       fail-fast: false
       matrix:
         cluster: [
-          {distribution: kind, version: v1.27.0}
+          {distribution: kind, version: v1.28.0}
         ] 
     env:
       APP_SLUG: deployment-orchestration
@@ -3468,7 +3580,7 @@ jobs:
         cluster: [
           {distribution: kind, version: v1.28.0},
           {distribution: openshift, version: 4.13.0-okd}
-        ] 
+        ]
     env:
       KOTS_NAMESPACE: replicated-sdk
     steps:
@@ -3780,7 +3892,6 @@ jobs:
       # testim tests
       - validate-existing-online-install-minimal
       - validate-smoke-test
-      - validate-minimal-rbac
       - validate-backup-and-restore
       - validate-no-required-config
       - validate-version-history-pagination
@@ -3794,6 +3905,7 @@ jobs:
       - validate-airgap-smoke-test
       - validate-config
       # non-testim tests
+      - validate-minimal-rbac
       - validate-minimal-rbac-override
       - validate-multi-namespace
       - validate-kots-pull
