validate kurl addon job in validate-success

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -1791,8 +1791,6 @@ jobs:
   validate-pr-tests:
     runs-on: ubuntu-20.04
     needs:
-      # kurl add-on
-      - validate-kurl-addon
       # testim tests
       - validate-existing-online-install-minimal
       - validate-smoke-test
@@ -1823,17 +1821,25 @@ jobs:
     steps:
       - run: echo "All PR tests passed"
 
-  # this job will validate that all pr-tests succeed and is used for the github branch protection rule
+  # this job will validate that the kurl add-on validation did not fail and that all pr-tests succeed
+  # it is used for the github branch protection rule
   validate-success:
     runs-on: ubuntu-20.04
-    needs: [ validate-pr-tests ]
+    needs:
+      - validate-kurl-addon
+      - validate-pr-tests
     if: always()
     steps:
-    # if the validate-pr-tests job was not successful, this job will fail
-    - name: fail if validate-pr-tests job failed
-      if: steps.validate-pr-tests.outcome != 'success'
-      run: exit 1
-    # if the validate-pr-tests job was successful, this job will succeed
-    - name: succeed if validate-pr-tests job succeeded
-      if: steps.validate-pr-tests.outcome == 'success'
-      run: echo "Validation succeeded"
+      # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
+      # if the validate-kurl-addon job failed or was cancelled, this job will fail. it's ok if this job was skipped
+      - name: fail if validate-kurl-addon job failed
+        if: steps.validate-kurl-addon.outcome == 'failed' || steps.validate-kurl-addon.outcome == 'cancelled'
+        run: exit 1
+      # if the validate-pr-tests job was not successful, this job will fail
+      - name: fail if validate-pr-tests job was skipped or failed
+        if: steps.validate-pr-tests.outcome != 'success'
+        run: exit 1
+      # if the validate-pr-tests job was successful, this job will succeed
+      - name: succeed if validate-pr-tests job succeeded
+        if: steps.validate-pr-tests.outcome == 'success'
+        run: echo "Validation succeeded"
