add PR e2e  validate-kots-helm-release-secret-migration

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -2279,7 +2279,7 @@ jobs:
           fi
 
           # verify that the helm release secret is created in the helm relase namespace
-          releaseSecret=kubectl get secret "$releaseSecretName" -n "$RELEASE_NAMESPACE"
+          releaseSecret=$(kubectl get secret "$releaseSecretName" -n "$RELEASE_NAMESPACE")
           if [ -z "$releaseSecret" ]; then
             echo "Failed to find the helm release secret in the $RELEASE_NAMESPACE namespace"
             echo "kotsadm logs:"
@@ -2288,9 +2288,19 @@ jobs:
           fi
 
           # verify that the release secret in app namepspace is deleted
-          oldReleaseSecret=kubectl get secret "$releaseSecretName" -n "$APP_SLUG"
+          oldReleaseSecret=$(kubectl get secret "$releaseSecretName" -n "$APP_SLUG")
           if [ -n "$oldReleaseSecret" ]; then
             echo "Found the helm release secret in the $APP_SLUG namespace"
+            echo "kotsadm logs:"
+            kubectl logs -l app=kotsadm --tail=100 --namespace "$APP_SLUG"
+            exit 1
+          fi
+
+          # verify that there are two helm release secrets in the helm release namespace
+          releaseSecretName=$(kubectl get secret -n "$RELEASE_NAMESPACE" -l owner=helm,name="$RELEASE_NAME" -o jsonpath='{.items[*].metadata.name}')
+          # if the helm release secrets are not 2 in the helm release namespace, fail
+          if [ "$(echo "$releaseSecretName" | wc -l)" -ne 2 ]; then
+            echo "Found more than two helm release secret in the $APP_SLUG namespace"
             echo "kotsadm logs:"
             kubectl logs -l app=kotsadm --tail=100 --namespace "$APP_SLUG"
             exit 1
