Replace postgres with rqlite

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -59,7 +59,7 @@ jobs:
         uses: actions/checkout@v2
       - name: Get tags
         id: get_tag
-        uses: ./actions/version-tag
+        uses: ./.github/actions/version-tag
 
 
   test-okteto-env:
@@ -315,7 +315,7 @@ jobs:
           docker push ttl.sh/automated-${{ github.run_id }}/minio:${{ steps.dotenv.outputs.minio_tag }}
 
 
-  push-postgres:
+  push-rqlite:
     runs-on: ubuntu-20.04
     needs: [ can-run-ci ]
     steps:
@@ -327,17 +327,11 @@ jobs:
         with:
           path: .image.env
 
-      - name: push postgres 10 for CI
+      - name: push rqlite for CI
         run: |
-          docker pull postgres:${{ steps.dotenv.outputs.POSTGRES_10_TAG }}
-          docker tag postgres:${{ steps.dotenv.outputs.POSTGRES_10_TAG }} ttl.sh/automated-${{ github.run_id }}/postgres:${{ steps.dotenv.outputs.POSTGRES_10_TAG }}
-          docker push ttl.sh/automated-${{ github.run_id }}/postgres:${{ steps.dotenv.outputs.POSTGRES_10_TAG }}
-
-      - name: push postgres 14 for CI
-        run: |
-          docker pull postgres:${{ steps.dotenv.outputs.POSTGRES_14_TAG }}
-          docker tag postgres:${{ steps.dotenv.outputs.POSTGRES_14_TAG }} ttl.sh/automated-${{ github.run_id }}/postgres:${{ steps.dotenv.outputs.POSTGRES_14_TAG }}
-          docker push ttl.sh/automated-${{ github.run_id }}/postgres:${{ steps.dotenv.outputs.POSTGRES_14_TAG }}
+          docker pull rqlite/rqlite:${{ steps.dotenv.outputs.RQLITE_TAG }}
+          docker tag rqlite/rqlite:${{ steps.dotenv.outputs.RQLITE_TAG }} ttl.sh/automated-${{ github.run_id }}/rqlite:${{ steps.dotenv.outputs.RQLITE_TAG }}
+          docker push ttl.sh/automated-${{ github.run_id }}/rqlite:${{ steps.dotenv.outputs.RQLITE_TAG }}
 
 
   push-dex:
@@ -426,7 +420,7 @@ jobs:
 
   validate-existing-online-install-minimal:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -456,7 +450,7 @@ jobs:
 
   validate-smoke-test:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -490,7 +484,7 @@ jobs:
 
   validate-minimal-rbac:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -524,7 +518,7 @@ jobs:
 
   validate-backup-and-restore:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -558,7 +552,7 @@ jobs:
 
   validate-no-required-config:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -592,7 +586,7 @@ jobs:
 
   validate-strict-preflight-checks:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -626,7 +620,7 @@ jobs:
 
   validate-version-history-pagination:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -660,7 +654,7 @@ jobs:
 
   validate-change-license:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -694,7 +688,7 @@ jobs:
 
   validate-helm-managed:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -730,7 +724,7 @@ jobs:
 
   validate-minimal-rbac-override:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -810,7 +804,7 @@ jobs:
 
   validate-multi-namespace:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -883,7 +877,7 @@ jobs:
 
   validate-kots-pull:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -969,7 +963,7 @@ jobs:
 
   validate-app-version-label:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1103,7 +1097,7 @@ jobs:
 
   validate-helm-install-order:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1177,7 +1171,7 @@ jobs:
 
   validate-yamlescape:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1251,7 +1245,7 @@ jobs:
 
   validate-no-redeploy-on-restart:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1349,7 +1343,7 @@ jobs:
 
   validate-kubernetes-installer-preflight:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1446,112 +1440,9 @@ jobs:
           aws-secret-access-key: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_SECRET_ACCESS_KEY }}'
 
 
-  validate-postgres-upgrade:
-    runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
-    strategy:
-      fail-fast: false
-      matrix:
-        k8s_version: [ v1.21.8-k3s2,v1.22.5-k3s2,v1.23.3-k3s1,v1.24.4-k3s1 ]
-    env:
-      APP_SLUG: upgrade-postgres
-      BASE_KOTS_VERSION: v1.77.0
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - uses: replicatedhq/action-k3s@main
-        with:
-          version: ${{ matrix.k8s_version }}
-
-      - name: download base kots version
-        run: |
-          curl -LO https://github.com/replicatedhq/kots/releases/download/$BASE_KOTS_VERSION/kots_linux_amd64.tar.gz \
-            && tar zxvf kots_linux_amd64.tar.gz \
-            && mv kots kots-$BASE_KOTS_VERSION
-
-      - name: download kots binary
-        uses: actions/download-artifact@v2
-        with:
-          name: kots
-          path: bin/
-
-      - run: chmod +x bin/kots
-
-      - name: run the test
-        run: |
-          set +e
-          echo ${{ secrets.UPGRADE_POSTGRES_LICENSE }} | base64 -d > license.yaml
-
-          # install using the base KOTS version
-
-          ./kots-$BASE_KOTS_VERSION \
-            install $APP_SLUG/automated \
-            --license-file license.yaml \
-            --no-port-forward \
-            --namespace $APP_SLUG \
-            --shared-password password
-
-          EXIT_CODE=$?
-          if [ $EXIT_CODE -ne 0 ]; then
-            echo "------pods:"
-            kubectl -n $APP_SLUG get pods
-            echo "------kotsadm logs"
-            kubectl logs -l app=kotsadm --tail=100 --namespace $APP_SLUG
-            exit $EXIT_CODE
-          fi
-
-          COUNTER=1
-          while [ "$(./kots-$BASE_KOTS_VERSION get apps --namespace $APP_SLUG | awk 'NR>1{print $2}')" != "ready" ]; do
-            COUNTER=$[$COUNTER +1]
-            if [ $COUNTER -gt 120 ]; then
-              echo "Timed out waiting for app to be ready"
-              ./kots-$BASE_KOTS_VERSION get apps --namespace $APP_SLUG
-              echo "kotsadm logs:"
-              kubectl logs -l app=kotsadm --tail=100 --namespace $APP_SLUG
-              exit -1
-            fi
-            sleep 1
-          done
-
-          # upgrade using the new KOTS version
-
-          ./bin/kots admin-console upgrade \
-            --namespace $APP_SLUG \
-            --kotsadm-registry ttl.sh \
-            --kotsadm-namespace automated-${{ github.run_id }} \
-            --kotsadm-tag 12h
-
-          if ! kubectl logs kotsadm-postgres-0 -c upgrade-postgres --namespace $APP_SLUG | grep -q "Upgrade Complete"; then
-            echo "kotsadm-postgres logs:"
-            kubectl logs -l app=kotsadm-postgres --all-containers --namespace $APP_SLUG
-            exit 1
-          fi
-
-          # make sure app is still installed and ready
-
-          if [ "$(./bin/kots get apps --namespace $APP_SLUG | awk 'NR>1{print $2}')" != "ready" ]; then
-            echo "App is not ready after the upgrade"
-            echo "kotsadm logs:"
-            kubectl logs -l app=kotsadm --tail=100 --namespace $APP_SLUG
-            exit 1
-          fi
-
-          printf "App is still installed and is ready after the upgrade\n\n"
-          ./bin/kots get apps --namespace $APP_SLUG
-
-      - name: Generate support bundle on failure
-        if: failure()
-        uses: ./.github/actions/generate-support-bundle
-        with:
-          kots-namespace: "$APP_SLUG"
-          aws-access-key-id: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_ACCESS_KEY_ID }}'
-          aws-secret-access-key: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_SECRET_ACCESS_KEY }}'
-
-
   validate-tag-and-digest:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1585,7 +1476,7 @@ jobs:
 
   validate-kots-push-images-anonymous:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
     strategy:
       fail-fast: false
     steps:
@@ -1608,7 +1499,7 @@ jobs:
 
   validate-min-kots-version:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres, generate-tag ]
+    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite, generate-tag ]
     env:
       APP_SLUG: min-kots-version
     strategy:
@@ -1663,7 +1554,7 @@ jobs:
 
   validate-target-kots-version:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres, generate-tag ]
+    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite, generate-tag ]
     strategy:
       fail-fast: false
       matrix:
@@ -1712,7 +1603,7 @@ jobs:
 
   validate-range-kots-version:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-postgres, generate-tag ]
+    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite, generate-tag ]
     strategy:
       fail-fast: false
       matrix:
@@ -1759,6 +1650,110 @@ jobs:
           fi
 
 
+  validate-postgres-to-rqlite-migration:
+    runs-on: ubuntu-20.04
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    strategy:
+      fail-fast: false
+      matrix:
+        k8s_version: [ v1.21.8-k3s2,v1.22.5-k3s2,v1.23.3-k3s1,v1.24.4-k3s1 ]
+    env:
+      APP_SLUG: postgres-to-rqlite
+      BASE_KOTS_VERSION: v1.57.0
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - uses: replicatedhq/action-k3s@main
+        with:
+          version: ${{ matrix.k8s_version }}
+
+      - name: download base kots version
+        run: |
+          curl -LO https://github.com/replicatedhq/kots/releases/download/$BASE_KOTS_VERSION/kots_linux_amd64.tar.gz \
+            && tar zxvf kots_linux_amd64.tar.gz \
+            && mv kots kots-$BASE_KOTS_VERSION
+
+      - name: download kots binary
+        uses: actions/download-artifact@v2
+        with:
+          name: kots
+          path: bin/
+
+      - run: chmod +x bin/kots
+
+      - name: run the test
+        run: |
+          set +e
+          echo ${{ secrets.POSTGRES_TO_RQLITE_LICENSE }} | base64 -d > license.yaml
+
+          # install using the base KOTS version
+
+          ./kots-$BASE_KOTS_VERSION \
+            install $APP_SLUG/automated \
+            --license-file license.yaml \
+            --port-forward=false \
+            --namespace $APP_SLUG \
+            --shared-password password
+
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "------pods:"
+            kubectl -n $APP_SLUG get pods
+            echo "------kotsadm logs"
+            kubectl logs -l app=kotsadm --tail=100 --namespace $APP_SLUG
+            exit $EXIT_CODE
+          fi
+
+          COUNTER=1
+          while [ "$(./kots-$BASE_KOTS_VERSION get apps --namespace $APP_SLUG | awk 'NR>1{print $2}')" != "ready" ]; do
+            COUNTER=$[$COUNTER +1]
+            if [ $COUNTER -gt 120 ]; then
+              echo "Timed out waiting for app to be ready"
+              ./kots-$BASE_KOTS_VERSION get apps --namespace $APP_SLUG
+              echo "kotsadm logs:"
+              kubectl logs -l app=kotsadm --tail=100 --namespace $APP_SLUG
+              exit -1
+            fi
+            sleep 1
+          done
+
+          # upgrade using the new KOTS version
+
+          ./bin/kots admin-console upgrade \
+            --namespace $APP_SLUG \
+            --kotsadm-registry ttl.sh \
+            --kotsadm-namespace automated-${{ github.run_id }} \
+            --kotsadm-tag 12h
+
+          if ! kubectl logs -l app=kotsadm --namespace $APP_SLUG | grep -q "Migrated from Postgres to rqlite successfully"; then
+            echo "Failed to find a successful migration log line"
+            echo "kotsadm logs:"
+            kubectl logs -l app=kotsadm --all-containers --namespace $APP_SLUG
+            exit 1
+          fi
+
+          # make sure app is still installed and ready
+
+          if [ "$(./bin/kots get apps --namespace $APP_SLUG | awk 'NR>1{print $2}')" != "ready" ]; then
+            echo "App is not ready after the upgrade"
+            echo "kotsadm logs:"
+            kubectl logs -l app=kotsadm --tail=100 --namespace $APP_SLUG
+            exit 1
+          fi
+
+          printf "App is still installed and is ready after the migration\n\n"
+          ./bin/kots get apps --namespace $APP_SLUG
+
+      - name: Generate support bundle on failure
+        if: failure()
+        uses: ./.github/actions/generate-support-bundle
+        with:
+          kots-namespace: "$APP_SLUG"
+          aws-access-key-id: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_ACCESS_KEY_ID }}'
+          aws-secret-access-key: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_SECRET_ACCESS_KEY }}'
+
+
   # this job will validate that all validate-* jobs succeed and is used for the github branch protection rule
   validate-success:
     runs-on: ubuntu-20.04
@@ -1788,7 +1783,7 @@ jobs:
       - validate-yamlescape
       - validate-no-redeploy-on-restart
       - validate-kubernetes-installer-preflight
-      - validate-postgres-upgrade
+      - validate-postgres-to-rqlite-migration
       # cli-only tests
       - validate-kots-push-images-anonymous
     steps:
