migrate to minio xl backend (#3624)
* migrate to minio xl backend

* add back s3 secret logic that was inadvertently removed

* address comments on migration scripts

* update generate-manifests build test

* don't delete scripts configmap if there are initcontainers

* udpate generate-manifests build-test

* don't remove migration scripts configmap

* rename migration vars

* rename migration work dir

* clean migration dir before starting

* add mc to GetOriginalAdminConsoleImages

* fix WaitForStatefulSetReady

* add minio xl migration status configmap

* create namespace before applying

* clean up build-test

* write timestamp to .migration file

* rename postgres to rqlite test to validate-kots-upgrade

* fix validate-pr-tests dependencies

* wait for kotsadm-minio-0 pod

* more edits to generate-manifests build-test

* sleep before checking for ready pods

* print kotsadm-minio logs on failure

* support registry flags for generate-manifests

* wait for kotsadm deployment to be ready

* wait 5m for kotsadm deployment after applying generated manifests

* bump minio image tag

* fix typo in configmap name when checking status

* use getRegistryConfig in generate-manifests

* update build-test for pr feedback

* constants for scripts and status configmap names

* do not clean emptydir and handle some edge cases

* re-use existing logger in generate-manifests

* remove old data before import

* clean migration directory after import

* export marker

* clean migration dir after marking complete

* mark complete before stopping minio

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -304,6 +304,25 @@ jobs:
           docker push ttl.sh/automated-${{ github.run_id }}/minio:${{ steps.dotenv.outputs.minio_tag }}
 
 
+  push-mc:
+    runs-on: ubuntu-20.04
+    needs: [ can-run-ci ]
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: load environment variables from .image.env
+        uses: falti/dotenv-action@v0.2
+        id: dotenv
+        with:
+          path: .image.env
+
+      - name: push minio client for e2e
+        run: |
+          docker pull minio/mc:${{ steps.dotenv.outputs.mc_tag }}
+          docker tag minio/mc:${{ steps.dotenv.outputs.mc_tag }} ttl.sh/automated-${{ github.run_id }}/mc:${{ steps.dotenv.outputs.mc_tag }}
+          docker push ttl.sh/automated-${{ github.run_id }}/mc:${{ steps.dotenv.outputs.mc_tag }}
+
+
   push-rqlite:
     runs-on: ubuntu-20.04
     needs: [ can-run-ci ]
@@ -409,7 +428,7 @@ jobs:
 
   validate-existing-online-install-minimal:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -439,7 +458,7 @@ jobs:
 
   validate-smoke-test:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -474,7 +493,7 @@ jobs:
 
   validate-minimal-rbac:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -509,7 +528,7 @@ jobs:
 
   validate-backup-and-restore:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -544,7 +563,7 @@ jobs:
 
   validate-no-required-config:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -579,7 +598,7 @@ jobs:
 
   validate-strict-preflight-checks:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -614,7 +633,7 @@ jobs:
 
   validate-version-history-pagination:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -649,7 +668,7 @@ jobs:
 
   validate-change-license:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -684,7 +703,7 @@ jobs:
 
   validate-helm-managed:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -721,7 +740,7 @@ jobs:
 
   validate-minimal-rbac-override:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -802,7 +821,7 @@ jobs:
 
   validate-multi-namespace:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -891,7 +910,7 @@ jobs:
 
   validate-kots-pull:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -978,7 +997,7 @@ jobs:
 
   validate-app-version-label:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1113,7 +1132,7 @@ jobs:
 
   validate-helm-install-order:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1188,7 +1207,7 @@ jobs:
 
   validate-yamlescape:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1263,7 +1282,7 @@ jobs:
 
   validate-no-redeploy-on-restart:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1362,7 +1381,7 @@ jobs:
 
   validate-kubernetes-installer-preflight:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1476,7 +1495,7 @@ jobs:
 
   validate-tag-and-digest:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1511,7 +1530,7 @@ jobs:
 
   validate-kots-push-images-anonymous:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
     steps:
@@ -1532,9 +1551,187 @@ jobs:
           ./bin/kots admin-console push-images ./hack/tests/small.airgap ttl.sh/automated-${{ github.run_id }}
 
 
+  validate-kots-admin-console-generate-manifests:
+    runs-on: ubuntu-20.04
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
+    strategy:
+      fail-fast: false
+      matrix:
+        k8s_version: [ v1.26.1-k3s1 ]
+    env:
+      APP_SLUG: minimal-rbac
+      BASE_KOTS_VERSION: v1.72.0
+      NAMESPACE: generate-manifests
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      
+      - name: download kots binary
+        uses: actions/download-artifact@v2
+        with:
+          name: kots
+          path: bin/
+      
+      - run: chmod +x bin/kots
+      
+      - name: run kots admin-console generate-manifests without k8s context
+        run: |
+          set +e
+          ./bin/kots admin-console generate-manifests -n $NAMESPACE --shared-password password
+      
+      - name: validate that ./admin-console exists and is not empty
+        run: |
+          set +e
+          if [ ! -d ./admin-console ]; then
+            echo "admin-console directory does not exist"
+            exit -1
+          fi
+          if [ -z "$(ls -A ./admin-console)" ]; then
+            echo "admin-console directory is empty"
+            exit -1
+          fi
+
+      - name: remove admin-console directory
+        run: rm -rf ./admin-console
+      
+      - name: install k3s
+        uses: replicatedhq/action-k3s@main
+        with:
+          version: ${{ matrix.k8s_version }}
+          arguments: ${{ startsWith(matrix.k8s_version, 'v1.22') && '--egress-selector-mode disabled' || '' }}
+      
+      - name: download base kots version
+        run: |
+          curl -LO https://github.com/replicatedhq/kots/releases/download/$BASE_KOTS_VERSION/kots_linux_amd64.tar.gz \
+            && tar zxvf kots_linux_amd64.tar.gz \
+            && mv kots kots-$BASE_KOTS_VERSION
+      
+      - name: create namespace
+        run: |
+          set +e
+          kubectl create namespace $NAMESPACE
+      
+      - name: run kots admin-console generate-manifests using base kots version with k8s context
+        run: |
+          set +e
+          ./kots-$BASE_KOTS_VERSION admin-console generate-manifests -n $NAMESPACE --shared-password password
+      
+      - name: apply the generated manifests
+        run: |
+          set +e
+          kubectl apply -f ./admin-console -n $NAMESPACE
+
+      - name: wait for the kotsadm-minio-0 pod to be created
+        run: |
+          set +e
+          COUNTER=1
+          while ! kubectl get pods -n $NAMESPACE | grep -q kotsadm-minio-0; do
+            COUNTER=$[$COUNTER +1]
+            if [ $COUNTER -gt 30 ]; then
+              echo "timed out waiting for kotsadm-minio-0 pod to be created"
+              exit -1
+            fi
+            sleep 1
+          done
+      
+      - name: wait for kotsadm-minio-0 pod to be ready
+        run: |
+          set +e
+          kubectl wait --for=condition=ready --timeout=180s pod/kotsadm-minio-0 -n $NAMESPACE
+
+      - name: wait for the kotsadm deployment to be ready
+        run: |
+          set +e
+          kubectl wait --for=condition=available --timeout=300s deployment/kotsadm -n $NAMESPACE
+      
+      - name: run kots admin-console generate-manifests using new kots version with k8s context
+        run: |
+          set +e
+          ./bin/kots admin-console generate-manifests -n $NAMESPACE \
+            --shared-password password \
+            --kotsadm-registry ttl.sh \
+            --kotsadm-namespace automated-${{ github.run_id }} \
+            --kotsadm-tag 24h
+      
+      - name: validate that ./admin-console/minio-statefulset.yaml has initContainers since a migration is needed
+        run: |
+          set +e
+          if [ -z "$(grep -E 'initContainers' ./admin-console/minio-statefulset.yaml)" ]; then
+            echo "admin-console/minio-statefulset.yaml does not have initContainers"
+            exit -1
+          fi
+      
+      - name: apply the generated manifests
+        run: |
+          set +e
+          kubectl apply -f ./admin-console -n $NAMESPACE
+      
+      - name: wait for kotsadm-minio-0 pod to be ready
+        run: |
+          set +e
+          sleep 10
+          kubectl wait --for=condition=ready --timeout=180s pod/kotsadm-minio-0 -n $NAMESPACE
+
+      - name: wait for the kotsadm deployment to be ready
+        run: |
+          set +e
+          kubectl wait --for=condition=available --timeout=300s deployment/kotsadm -n $NAMESPACE
+      
+      - name: run kots admin-console generate-manifests using new kots version with k8s context
+        run: |
+          set +e
+          ./bin/kots admin-console generate-manifests -n $NAMESPACE \
+            --shared-password password \
+            --kotsadm-registry ttl.sh \
+            --kotsadm-namespace automated-${{ github.run_id }} \
+            --kotsadm-tag 24h
+      
+      - name: validate that ./admin-console/minio-statefulset.yaml does not have initContainers since a migration is not needed
+        run: |
+          set +e
+          if [ -n "$(grep -E 'initContainers' ./admin-console/minio-statefulset.yaml)" ]; then
+            echo "admin-console/minio-statefulset.yaml has initContainers"
+            exit -1
+          fi
+      
+      - name: apply the generated manifests
+        run: |
+          set +e
+          kubectl apply -f ./admin-console -n $NAMESPACE
+      
+      - name: wait for kotsadm-minio-0 pod to be ready
+        run: |
+          set +e
+          sleep 10
+          kubectl wait --for=condition=ready --timeout=180s pod/kotsadm-minio-0 -n $NAMESPACE
+
+      - name: wait for the kotsadm deployment to be ready
+        run: |
+          set +e
+          kubectl wait --for=condition=available --timeout=300s deployment/kotsadm -n $NAMESPACE
+
+      - name: print pods and logs on failure
+        if: failure()
+        run: |
+          echo "------pods:"
+          kubectl -n $NAMESPACE get pods
+          echo "------kotsadm logs"
+          kubectl logs -l app=kotsadm --tail=100 --namespace $NAMESPACE
+          echo "------kotsadm-minio logs"
+          kubectl logs -l app=kotsadm-minio --tail=100 --namespace $NAMESPACE
+
+      - name: Generate support bundle on failure
+        if: failure()
+        uses: ./.github/actions/generate-support-bundle
+        with:
+          kots-namespace: "$APP_SLUG"
+          aws-access-key-id: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_ACCESS_KEY_ID }}'
+          aws-secret-access-key: '${{ secrets.E2E_SUPPORT_BUNDLE_AWS_SECRET_ACCESS_KEY }}'
+
+
   validate-min-kots-version:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite, generate-tag ]
+    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite, generate-tag ]
     env:
       APP_SLUG: min-kots-version
     strategy:
@@ -1590,7 +1787,7 @@ jobs:
 
   validate-target-kots-version:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite, generate-tag ]
+    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite, generate-tag ]
     strategy:
       fail-fast: false
       matrix:
@@ -1640,7 +1837,7 @@ jobs:
 
   validate-range-kots-version:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite, generate-tag ]
+    needs: [ enable-tests, can-run-ci, build-e2e, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite, generate-tag ]
     strategy:
       fail-fast: false
       matrix:
@@ -1688,9 +1885,9 @@ jobs:
           fi
 
 
-  validate-postgres-to-rqlite-migration:
+  validate-kots-upgrade:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1765,10 +1962,21 @@ jobs:
             --kotsadm-namespace automated-${{ github.run_id }} \
             --kotsadm-tag 24h
 
+          # verify that the postgres to rqlite migration was successful
+
           if ! kubectl logs -l app=kotsadm --namespace $APP_SLUG | grep -q "Migrated from Postgres to rqlite successfully"; then
             echo "Failed to find a successful migration log line"
             echo "kotsadm logs:"
             kubectl logs -l app=kotsadm --all-containers --namespace $APP_SLUG
+            exit 1
+          fi
+
+          # verify that the minio migration happened
+
+          if [ -z "$(kubectl get statefulset kotsadm-minio -n $APP_SLUG -o jsonpath='{.spec.template.spec.initContainers}')" ]; then
+            echo "Failed to find initContainers in the kotsadm-minio statefulset"
+            echo "kotsadm-minio statefulset:"
+            kubectl get statefulset kotsadm-minio -n $APP_SLUG -o yaml
             exit 1
           fi
 
@@ -1794,7 +2002,7 @@ jobs:
 
   validate-multi-app-install:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -1829,7 +2037,7 @@ jobs:
 
   validate-airgap-smoke-test:
     runs-on: ubuntu-20.04
-    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-rqlite ]
+    needs: [ enable-tests, can-run-ci, build-kots, build-e2e, build-kurl-proxy, build-migrations, push-minio, push-mc, push-rqlite ]
     strategy:
       fail-fast: false
       matrix:
@@ -2122,7 +2330,7 @@ jobs:
       - validate-yamlescape
       - validate-no-redeploy-on-restart
       - validate-kubernetes-installer-preflight
-      - validate-postgres-to-rqlite-migration
+      - validate-kots-upgrade
       - validate-remove-app
       - validate-registry-check
       # cli-only tests
