fix: namespace field in HelmChart custom resource does not work when useHelmInstall is set to true (#3657)
* fix: namespace field in HelmChart custom resource does not work when useHelmInstall is set to true

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -813,6 +813,10 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
+      - uses: azure/setup-helm@v3
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
       - uses: replicatedhq/action-k3s@main
         with:
           version: ${{ matrix.k8s_version }}
@@ -862,8 +866,19 @@ jobs:
             sleep 1
           done
 
-          printf "App is installed successfully and is ready\n\n"
-          ./bin/kots get apps --namespace $APP_SLUG
+          # validate that helm charts installed using the native helm workflow were deployed via the helm CLI correctly
+
+          if [ ! helm ls -n postgres-test | awk 'NR>1{print $1}' | grep -q postgresql ]; then
+            printf "postgresql helm release not found in postgres-test namespace\n\n"
+            helm ls -n postgres-test
+            exit 1
+          fi
+
+          if [ ! helm ls -n $APP_SLUG | awk 'NR>1{print $1}' | grep -q private-chart ]; then
+            printf "private-chart helm release not found in $APP_SLUG namespace\n\n"
+            helm ls -n $APP_SLUG
+            exit 1
+          fi
 
       - name: Generate support bundle on failure
         if: failure()
