use HELM_APP_NAMESPACES

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -2536,6 +2536,7 @@ jobs:
           set +e
           
           echo ${{ secrets.REMOVE_APP_LICENSE }} | base64 -d > license.yaml
+          HELM_APP_NAMESPACES=(postgres-test redis-test $APP_SLUG)
           APP_NAMESPACES=(postgres-test redis-test nginx-test rabbitmq-system $APP_SLUG)
 
           ./bin/kots \
@@ -2582,11 +2583,13 @@ jobs:
             exit 1
           fi
 
-          if [ "$(kubectl get secret -A --field-selector type=helm.sh/release.v1 --ignore-not-found | wc -l | tr -d '\n')" != "0" ]; then
-            printf "Application Helm release secrets are still found in the cluster\n\n"
-            kubectl get secret -A --field-selector type=helm.sh/release.v1
-            exit 1
-          fi
+          for ns in "${HELM_APP_NAMESPACES[@]}"; do
+            if [ "$(kubectl get secret -n "$ns" --field-selector type=helm.sh/release.v1 --ignore-not-found | wc -l | tr -d '\n')" != "0" ]; then
+              printf "Application Helm release secrets are still found in the namepspace %s\n\n" "$ns"
+              kubectl get secret -n "$ns" --field-selector type=helm.sh/release.v1
+              exit 1
+            fi
+          done
 
           # re-install and test that running the remove command without --undeploy does _not_ delete any resources from the cluster
 
@@ -2640,11 +2643,13 @@ jobs:
             exit 1
           fi
 
-          if [ "$(kubectl get secret -A --field-selector type=helm.sh/release.v1 --ignore-not-found | wc -l | tr -d '\n')" == "0" ]; then
-            printf "Application Helm release secrets are not found\n\n"
-            kubectl get secret -A --field-selector type=helm.sh/release.v1
-            exit 1
-          fi
+          for ns in "${HELM_APP_NAMESPACES[@]}"; do
+            if [ "$(kubectl get secret -n "$ns" --field-selector type=helm.sh/release.v1 --ignore-not-found | wc -l | tr -d '\n')" == "0" ]; then
+              printf "Application Helm release secrets are not found in namepspace %s\n\n" "$ns"
+              kubectl get secret -n "$ns" --field-selector type=helm.sh/release.v1
+              exit 1
+            fi
+          done
 
       - name: Generate support bundle on failure
         if: failure()
